[MODEL]
base_model      = "AutoEncoder"
model_save_path = "./"
batch_size      = 55
random_seed     = 42
#loss_function   = "BCEWithLogitsLoss"#"CrossEntropyLoss"#"MSELoss"
loss_functions   = ["MSELoss"]
#loss_functions   = ["MSELoss", "MSELoss", "MSELoss"]
loss_weights    = 1
#activation      = "Sigmoid"
activations      = ["Identity"]
#activations      = ["Identity", "Identity", "Identity"]
max_epochs      = 300
precision       = 32
#backbone        = "densenet121"
#backbone        = "resnet10"
#backbone        = "totalsegmentator"
backbone        = "simpleCNN"
backbone_folder = "/home/dgs1/Software/Miguel/OutcomePrediction/TotalSegmentatorBackbone"
pretrained      = false
backbone_fixed  = false
dropout_prob    = 0.0  #dropout
#wf              = 4
#depth           = 6
inference       = true
emb_size        = 1000
devices         = [0]
learning_rate   = 1e-3
#learning_rate   = 3e-4
lr_step_size    = 40
lr_gamma        = 0.7
linear_out      = 124
bottleneck      = [2, 2, 2]
backbone_out_c  = 512
classifier_in   = 1
classifier_config = []
# modes           = 'regression'#'classification'
modes            = ['regression']
#modes            = ['regression', 'regression', 'regression']

[MODEL_PARAMETERS]
spatial_dims  = 3
#block_config  = [1, 2, 4, 1]  # for densenet
#in_channels   = 2  # for densenet
#out_channels  = 1  # for densenet
#dropout_prob  = 0.0  # for densenet
n_input_channels = 1  # for resnet
num_classes = 1  # for resnet

[Dose_MODEL_PARAMETERS]
in_channels = 1
wf          = 3
depth       = 3

[MODALITY]
CT          = 1
RTDOSE	    = 0
PET         = 0
RTSTRUCT    = 0

[RECORDS]
records     = 0

[DATA]
format                  = "nii.gz"
data_folder             = "/home/dgs1/data/Nifty_Data/RTOG_0617/Downsized_Version_160x160x32"
#log_folder              = "/home/dgs1/Software/Miguel/OutcomePrediction/Logs/OnlyCT/MultiplePrediction/TotalSegmentator0617+LUNG1+UCLH"
#log_folder              = "/home/dgs1/Software/Miguel/OutcomePrediction/Logs/CT&Target&Dose/SurvivalPrediction/TotalSegmentator/2x2x2"
#log_folder              = "/home/dgs1/Software/Miguel/OutcomePrediction/Logs/CT&Target&Dose/SurvivalPrediction/TotalSegmentator/2x2x2/RTOG0617"
log_folder              = "/home/dgs1/Software/Miguel/OutcomePrediction/Logs/OnlyCT/GTVPrediction/SimpleCNN"
#log_folder              = "/home/dgs1/Software/Miguel/OutcomePrediction/Logs/Debug/RUnet-3ch-less-less"
#clinical_table_path     = "/home/dgs1/Software/Miguel/RTOG+LUNG1+UCLH_clinical_reduced_converted_patid_changed.csv"
clinical_table_path     = "/home/dgs1/Software/Miguel/NCT00533949-D1-Dataset.csv"
data_structure          = "rtog"
CT_path                 = ''
RTDOSE_path             = ''
RTSTRUCT_path           = 'struct_TS/'
n_per_sample            = 5000
n_classes               = 1
n_channel               = 1
sub_patch_size          = 16
dim                     = [160, 160, 32]
train_size              = 0.7
val_size                = 0.3
# target                  = "survival_months"#"age"#"volume_gtv"#"survival_months"
# target                  = "IntervalStartRTDateLastFU
target                  = "volume_gtv"
threshold               = 24
censor_label            = "survival_status"
censored_value          = 1
#additional_targets      = ["age", "volume_gtv"]
additional_targets      = []
include_censored        = true
exclude_event_nan       = true
subject_label           = "patid"
structs                 = 'ptv'
#multichannel            = true
multichannel            = false
patient_ids_file_path   = "SubjectListRTOG0617WithPTVOriginal.csv"
#clinical_cols           = ['age', 'volume_gtv', 'dmax_ptv', 'received_conc_chemo', 'zubrod', 'histology', 'gender', 'rt_technique', 'egfr_hscore_200']
#clinical_cols           = ['age', 'volume_gtv', 'dmax_ptv', 'gender']
clinical_cols           = []
#continuous_cols         = ['age', 'volume_gtv', 'dmax_ptv']
#categorical_cols        = ['received_conc_chemo', 'zubrod', 'histology', 'gender', 'rt_technique', 'egfr_hscore_200']
#categorical_cols        = ['gender']
categorical_cols        = []
imputation              = 'mice'
impute_addit_target     = true
crop_foreground         = false  #not in use, it does nothing atm

[RUN]
# random_state        = 1
# random_state        = 2
random_state        = 4
bootstrap_n         = 1
run_additional_info = 'After passing the prediction through an activation function before calling the metrics'

[CRITERIA]
#survival_status = 1
#arm             = 1

[CHECKPOINT]
monitor         = "val_loss" #"val_acc_epoch"
mode            = "max"
matrix          = ['ROC', 'Specificity']

[FILTER]
#patient_id = ['0617-444138','0617-449451']
